version: '3.8'
        
services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    container_name: my-database-liferay

  liferay:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: my-liferay
    image: 'liferay'
    depends_on:
      - database
    ports:
      - "${LFR_DEBUG_ENV}:8000"
      - "${LFR_PORT_ENV}:8080"